```
FROM tomcat
LABEL Application="Ecomerce"
RUN apt update && apt install openjdk-11-jdk -y && apt install git -y
RUN git clone https://github.com/hkhcoder/vprofile-project.git 
WORKDIR vprofile-project
ADD https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz .
RUN apt mvn install -y && mvn package
RUN cp target/vprofile-v2.war /usr/local/tomcat/webapps/vprofile-v2.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
```

## Docker MSB 


```
FROM openjdk:11 AS BUILD_IMAGE
RUN apt update && apt install maven -y
RUN git clone https://github.com/devopshydclub/vprofile-project.git
RUN cd vprofile-project && git checkout docker && mvn install
 
FROM tomcat:9-jre11
 
RUN rm -rf /usr/local/tomcat/webapps/*
 
COPY --from=BUILD_IMAGE vprofile-project/target/vprofile-v2.war /usr/local/tomcat/webapps/ROOT.war
 
EXPOSE 8080
CMD ["catalina.sh", "run"]
```

```
FROM alpine/git AS VCS
RUN cd / && git clone https://github.com/spring-projects/spring-petclinic.git
 
FROM maven:3.9-amazoncorretto-17 AS Builder
COPY --from=VCS /spring-petclinic /spring-petclinic
RUN cd /spring-petclinic && mvn package
 
FROM amazoncorretto:17-alpine-jdk
LABEL authour="Asee" project="spc" org="learning"
ARG HOME_DIR=/spring-petclinic
WORKDIR ${HOME_DIR}
COPY --from=Builder /spring-petclinic/target/spring-*.jar ${HOME_DIR}/spring-petclinc.jar
EXPOSE 8080
CMD [ "java","-jar","spring-petclinc.jar" ]
```