1. Write Dockerfile
```
  FROM tomcat
  RUN mkdir /app
  RUN apt-get update
  RUN apt-get install tree -y
  RUN apt-get install git -y 
  RUN echo "RUN/CMD demo"
  CMD ["echo","CMD/RUN demo"] 
```
2. Build Docker Image ```docker image build -t run-cmd:01 .```
3. docker container 




