version: '3.9' 
services: 
  database:
    image: "mongo"
    volumes: 
      - database:/data/db
    networks: 
      - alpine 
    deploy:
      replicas: 3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  backend: 
    image: "backend"
    volumes: 
      - backend:/app
    networks: 
      - alpine
    deploy:
      replicas: 3
volumes: 
  database:
  backend:
networks:
  alpine: 
